use strum_macros::{AsRefStr, EnumString};

#[derive(Default, Debug, Copy, Clone, AsRefStr, PartialEq, EnumString)]
pub enum Engraving {
    #[default]
    Unknown = 0,
    Mayhem = 125,
    #[strum(serialize = "Berserker Technique")]
    BerserkerTechnique = 188,
    #[strum(serialize = "Rage Hammer")]
    RageHammer = 196,
    #[strum(serialize = "Gravity Training")]
    GravityTraining = 197,
    #[strum(serialize = "Combat Readiness")]
    CombatReadiness = 224,
    #[strum(serialize = "Lone Knight")]
    LoneKnight = 225,
    Judgment = 282,
    #[strum(serialize = "Blessed Aura")]
    BlessedAura = 283,
    Predator = 309,
    Punisher = 310,
    #[strum(serialize = "Grace of the Empress")]
    GraceOfTheEmpress = 200,
    #[strum(serialize = "Order of the Emperor")]
    OrderOfTheEmperor = 201,
    #[strum(serialize = "Master Summoner")]
    MasterSummoner = 198,
    #[strum(serialize = "Communication Overflow")]
    CommunicationOverflow = 199,
    #[strum(serialize = "True Courage")]
    TrueCourage = 194,
    #[strum(serialize = "Desperate Salvation")]
    DesperateSalvation = 195,
    #[strum(serialize = "Igniter")]
    Igniter = 293,
    #[strum(serialize = "Reflux")]
    Reflux = 294,
    #[strum(serialize = "First Intention")]
    FirstIntention = 189,
    #[strum(serialize = "Esoteric Skill Enhancement")]
    EsotericSkillEnhancement = 127,
    #[strum(serialize = "Ultimate Skill: Taijutsu")]
    UltimateSkillTaijutsu = 190,
    #[strum(serialize = "Shock Training")]
    ShockTraining = 191,
    #[strum(serialize = "Energy Overflow")]
    EnergyOverflow = 256,
    #[strum(serialize = "Robust Spirit")]
    RobustSpirit = 257,
    #[strum(serialize = "Pinnacle")]
    Pinnacle = 276,
    #[strum(serialize = "Control")]
    Control = 277,
    #[strum(serialize = "Deathblow")]
    Deathblow = 291,
    #[strum(serialize = "Esoteric Flurry")]
    EsotericFlurry = 292,
    #[strum(serialize = "Brawl King Storm")]
    BrawlKingStorm = 314,
    #[strum(serialize = "Asura's Path")]
    AsurasPath = 315,
    #[strum(serialize = "Remaining Energy")]
    RemainingEnergy = 278,
    #[strum(serialize = "Surge")]
    Surge = 279,
    #[strum(serialize = "Perfect Suppression")]
    PerfectSuppression = 280,
    #[strum(serialize = "Demonic Impulse")]
    DemonicImpulse = 281,
    #[strum(serialize = "Hunger")]
    Hunger = 286,
    #[strum(serialize = "Lunar Voice")]
    LunarVoice = 287,
    #[strum(serialize = "Full Moon Harvester")]
    FullMoonHarvester = 311,
    #[strum(serialize = "Night's Edge")]
    NightsEdge = 312,
    #[strum(serialize = "Loyal Companion")]
    LoyalCompanion = 258,
    #[strum(serialize = "Death Strike")]
    DeathStrike = 259,
    #[strum(serialize = "Pistoleer")]
    Pistoleer = 192,
    #[strum(serialize = "Enhanced Weapon")]
    EnhancedWeapon = 129,
    #[strum(serialize = "Firepower Enhancement")]
    FirepowerEnhancement = 130,
    #[strum(serialize = "Barrage Enhancement")]
    BarrageEnhancement = 193,
    #[strum(serialize = "Arthetinean Skill")]
    ArthetineanSkill = 284,
    #[strum(serialize = "Evolutionary Legacy")]
    EvolutionaryLegacy = 285,
    #[strum(serialize = "Peacemaker")]
    Peacemaker = 289,
    #[strum(serialize = "Time to Hunt")]
    TimeToHunt = 290,
    #[strum(serialize = "Recurrence")]
    Recurrence = 305,
    #[strum(serialize = "Full Bloom")]
    FullBloom = 306,
    #[strum(serialize = "Wind Fury")]
    WindFury = 307,
    #[strum(serialize = "Drizzle")]
    Drizzle = 308,
}